import { Item } from "@/lib/types";

export const items: Item[] = [
  {
    slug: "rolex-gmt-rootbeer-2021",
    title: "GMT-Master II Rootbeer",
    brand: "Rolex",
    line: "Professional",
    season: "2021",
    era: "2020s",
    size: "40mm",
    price: 17800,
    conditionScore: 9,
    conditionNotes: "Full set, light hairlines, serviced 2024",
    authLevel: "verified",
    origin: "NYC Collector",
    originCard: {
      material: "Everose steel, Oyster bracelet",
      tech: "Cal. 3285, 70h power reserve",
      story: "Sourced from trusted collector with purchase receipts",
      dyeFinish: "Factory",
    },
    status: "live",
    features: ["gmt", "oyster", "everose"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1400&q=90",
        type: "main",
      },
      {
        url: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=90",
        type: "detail",
      },
    ],
    techSpec: [
      { key: "Movement", value: "Cal. 3285 automatic" },
      { key: "Case", value: "40mm Everose Oystersteel" },
      { key: "Waterproof", value: "100m" },
    ],
    styleNotes: "Pairs well with muted palettes; subtle rose tone.",
  },
  {
    slug: "goyard-st-louis-pm-grey",
    title: "St Louis PM",
    brand: "Goyard",
    line: "Heritage",
    season: "2019",
    era: "2010s",
    size: "PM",
    price: 1850,
    conditionScore: 8,
    conditionNotes: "With dustbag, minor patina on handles",
    authLevel: "verified",
    origin: "Paris Drop",
    originCard: {
      material: "Goyardine canvas, leather trim",
      tech: "Hand-painted chevron",
      story: "Consigned from Paris boutique client",
      dyeFinish: "Grey / handpaint",
    },
    status: "live",
    features: ["tote", "lightweight"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1400&q=90",
        type: "main",
      },
      {
        url: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=1200&q=90",
        type: "label",
      },
    ],
    techSpec: [
      { key: "Material", value: "Goyardine coated canvas" },
      { key: "Size", value: "PM" },
      { key: "Included", value: "Dustbag" },
    ],
  },
  {
    slug: "nike-dunk-sb-parra",
    title: "Dunk Low Parra",
    brand: "Nike SB",
    line: "Parra",
    season: "2021",
    era: "2020s",
    size: "US 10",
    price: 320,
    conditionScore: 8,
    conditionNotes: "Light wear, no box",
    authLevel: "verified",
    origin: "LA Skateshop",
    originCard: {
      material: "Leather/suede",
      tech: "Zoom Air insole",
      story: "Trade-in from team rider",
      dyeFinish: "Multicolor overlays",
    },
    status: "live",
    features: ["sb", "collab"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1400&q=90",
        type: "main",
      },
      {
        url: "https://images.unsplash.com/photo-1508183721372-b3f2e0e7f2bf?auto=format&fit=crop&w=1200&q=90",
        type: "tag",
      },
    ],
    techSpec: [
      { key: "Upper", value: "Leather/suede" },
      { key: "Insole", value: "Zoom Air" },
      { key: "Release", value: "Parra collab 2021" },
    ],
  },
  {
    slug: "leica-m10-p",
    title: "M10-P Black Chrome",
    brand: "Leica",
    line: "M",
    season: "2018",
    era: "2010s",
    size: "Body only",
    price: 5900,
    conditionScore: 7,
    conditionNotes: "CLA 2023, patina on brass edges",
    authLevel: "verified",
    origin: "Berlin Studio",
    originCard: {
      material: "Brass top plate, magnesium body",
      tech: "24 MP CMOS, Maestro II",
      story: "Studio camera with service records",
      dyeFinish: "Black chrome",
    },
    status: "live",
    features: ["rangefinder", "quiet-shutter"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1526178616484-4aa1f6c2c8aa?auto=format&fit=crop&w=1400&q=90",
        type: "main",
      },
      {
        url: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=1200&q=90",
        type: "detail",
      },
    ],
    techSpec: [
      { key: "Sensor", value: "24 MP full-frame CMOS" },
      { key: "Shutter", value: "Mechanical 1/4000" },
      { key: "Notes", value: "Whisper-quiet advance" },
    ],
    styleNotes: "Patina-friendly brass; pairs with 35mm Summilux.",
  },
];
